### ISSUE TITLE
Comment on code block

### ISSUE THREAD

**Issue by feldsam** [kategarshyna/custom_php_calendar#1]
https://github.com/kategarshyna/custom_php_calendar/blob/d8d06e8a7dae5868e40da02c3ee04b7efdea77ac/Calendar.php#L102

Hello Kateryna, I am Kristian from tlustyco.com.

When I lookin ginto your code I see unnecessary if else if else code blocks. Please clenup code, you can use

```
if(something){
  return var;
}

if(something_orher){
  return var2;
}
```

return exist execution of that method, so u dont need to do else block. Code will be more readable and managable.

**Comment by feldsam** [comment]
Please review whole class and fix this problem.

**Comment by kategarshyna** [comment]
Hi Kristian,
I have updated the code, please check again

**Comment by feldsam** [comment]
this block is also unnecesary complicated

https://github.com/kategarshyna/custom_php_calendar/blob/4774c662ccd673054e1212331d279d75f75a9d87/Calendar.php#L49


you can set class var to false by default and add just if when you set ti to true

**Comment by kategarshyna** [comment]
updated
